language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -e git+git://github.com/olegpidsadnyi/pytest-bdd.git#egg=pytest-bdd; python setup.py develop"
# # command to run tests
script: python setup.py test
notifications:
    email:
        - bubenkoff@gmail.com
